name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        # echo $PATH
        # echo 'export PATH="$HOME/.fly/bin:$PATH"' >> $GITHUB_ENV
        # export FLYCTL_INSTALL="/home/runner/.fly" >> $GITHUB_ENV
        # export PATH="$FLYCTL_INSTALL/bin:$PATH" >> $GITHUB_ENV
        echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
        echo "PATH=$FLYCTL_INSTALL/bin:$PATH" >> $GITHUB_ENV
        

    - name: Check PATH
      run: |
        echo $PATH
        echo 'export PATH="$HOME/.fly/bin:$PATH"' >> $GITHUB_ENV
        echo $PATH

    - name: Debug installation
      run: |
        echo "PATH: $PATH"
        ls -l $HOME/.fly/bin

    - name: Log in to Fly.io
      run: |
        export PATH="$HOME/.fly/bin:$PATH"  # Ensuring PATH is updated in the current shell
        echo "PATH: $PATH"  # Debugging output to verify PATH
        ls -l $HOME/.fly/bin  # Verify the binary is there and executable
        flyctl auth token --access-token ${{ secrets.FLYIO }}

      

    - name: Deploy to Fly.io
      run: |
        export PATH="$HOME/.fly/bin:$PATH"  # Ensuring PATH is updated in the current shell
        flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLYIO }}
